### ISSUE TITLE
rolunksd.jade nem fordítódik le

### ISSUE THREAD

**Issue by DecentM** [Krishtof/TB#2]
[root@testbirds staging.testbirds.hu]# jade rolunksd.jade

Warning: missing space before text for line 29 of jade file "rolunksd.jade"
Warning: missing space before text for line 43 of jade file "rolunksd.jade"

/usr/lib/node_modules/jade/lib/runtime.js:240
  throw err;
        ^
Error: rolunksd.jade:189
    187|                        setTimeout( function() {
    188|                        loader.hide();
  > 189|                  linkTag = $(ev.target).is('a')? $(ev.target) : $(ev.target).parents('a');
    190|                  link = $(linkTag).attr('href');
    191|                  document.location.href = link;
    192|                        }, 1000 );

Invalid indentation, you can use tabs or spaces but not both
    at Object.Lexer.indent (/usr/lib/node_modules/jade/lib/lexer.js:790:15)
    at Object.Lexer.next (/usr/lib/node_modules/jade/lib/lexer.js:941:15)
    at Object.Lexer.lookahead (/usr/lib/node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/usr/lib/node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/usr/lib/node_modules/jade/lib/parser.js:79:17)
    at Parser.block (/usr/lib/node_modules/jade/lib/parser.js:725:30)
    at Parser.tag (/usr/lib/node_modules/jade/lib/parser.js:838:24)
    at Parser.parseTag (/usr/lib/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/usr/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/usr/lib/node_modules/jade/lib/parser.js:729:25)

**Comment by DecentM** [comment]
Először a dev branchon voltam, gh-pagesben is ez van
